### ISSUE TITLE
Can we get installation instructions?

### ISSUE THREAD

**Issue by EverybodyKurts** [millenomi/afloat#10]
Hey guys,

I love afloat and want to update the software for Mavericks. I'm wondering if you guys could include a readme.md or something along those lines that includes instructions on how to install the software.

Thanks!

**Comment by mrfrankus** [comment]
Hi Kurt, 

Far from being any sort of official recipe, here is an outline of what you might expect to need to tackle: 
1. Get SIMBL from culater.net ( URL is: http://culater.net/software/SIMBL/SIMBL.php ) and install it on your Mac
2. Download and Install Xcode (from Apple) on your Mac
3. Fetch the afloat source from its GitHub repository ( URL is: https://github.com/millenomi/afloat )
4. Once you compile the source using Xcode you will end up with a package named: "Afloat.bundle"
5. Place the bundle (see item 4) under "/Library/Application Support/SIMBL/Plugins" if you mean to offer Afloat to all users on your Mac, or simply under "~/Library/Application Support/SIMBL/Plugins" if you're the only one that will use it, it's up to you.

You can also find some related KB articles here: 
http://infinite-labs.net/kb/

Hope this helps!
f.

Note: If ever you don't feel comfortable with using Xcode to compile the code yourself, perhaps I might be persuaded to zip up my own copy of the 2.4 bundle and share it with you (no strings attached) as a last resort, though preferably you would be better off working directly from the official source code.

**Comment by rsilvestre** [comment]
it's perfectly working with EasySIMBL : https://www.macupdate.com/app/mac/44354/easysimbl or https://github.com/norio-nomura/EasySIMBL

just drag'n drop aFloat.bundle in EasySIMBL

Works perfectly on Mavericks.

**Comment by millenomi** [comment]
Indeed, a standard compiled distribution was removed to make it clear that this is no longer intended for those who don't have the means of at least facing the inevitable amount of trouble that follows.

The instructions above are 100% correct. Thanks! ‡

**Comment by rsilvestre** [comment]
@mrfrankus Why you don't put your instruction in a ReadMe.md file? It is easy for a programmer to compile and use afloat, but for regular people it's not easy at all...

**Comment by EverybodyKurts** [comment]
Millenomi, are you accepting pull requests? I can simply throw together a readme.md and submit it. Won't be too hard!

**Comment by EverybodyKurts** [comment]
BTW, thanks everybody!

**Comment by aemonge** [comment]
Why don't you create a read.me file with this instructions? Or on the github wiki ? I've got here totally by chance xD

**Comment by aemonge** [comment]
Also, after compiling I can' seam to find the *.bundle file

**Comment by eduard-un** [comment]
@aemonge: Same here I do this in Xcode: Open the project, go to Product > Build and nothing, is this not the correct way? I really like to be ablet o keep a spred sheet always active.

**Comment by aemonge** [comment]
@eduard-ungureanu  I haven't found any work a round yet ...

**Comment by eduard-un** [comment]
@aemonge nope mate, sorry, I even decide not to spend hours, on stuff like building something with xcode, it's clear that the instructions are for developers not for normal users! I'm sorry.

**Comment by mrkapqa** [comment]
hello ,

on Powermac G4 - osx Leopard 10.5.8

1.i downloaded Afloat-Master
2. unzipped it
3. went into directory and run  -   xcodebuild -configuration Release install
4. got this message: 016-07-17 14:08:11.764 xcodebuild[197:613] NOTE: Referenced project AfloatScripting was written by a newer Xcode version (46) -- temporarily downgrading it (without modifying project file)
(NOTE: project Afloat was written by a newer Xcode version (46) -- temporarily downgrading it (without modifying project file))

=== BUILDING NATIVE TARGET AfloatScripting OF PROJECT AfloatScripting WITH CONFIGURATION Release ===

Checking Dependencies...
error: There is no SDK with the name or path 'macosx'
*\* BUILD FAILED **

any idea on how to install Afloat on Leopard ?

thanks

richie
