### ISSUE TITLE
dude common, lets make it support sublime text 2!

### ISSUE THREAD

**Issue by LeonFedotov** [millenomi/afloat#2]

**Comment by clarkewd** [comment]
+1

**Comment by ProLoser** [comment]
http://sublimetext.userecho.com/topic/131481-keep-afloat-simbl-support/

**Comment by hairarrow** [comment]
:+1: 

"Can I, like, upvote his issue or something?"

**Comment by hairarrow** [comment]
I don't know what I did or how it happened, but ST 2 v2.0.2 started working with Afloat

**Comment by millenomi** [comment]
Afloat will not bend over to support apps. If the app doesn't seem to support Afloat, it is not Afloat's job to correct the way it interacts with Cocoa.
