### ISSUE TITLE
Afloat causes hang in Chromium and freeciv-gtk2 on El Capitan

### ISSUE THREAD

**Issue by alexdelorenzo** [millenomi/afloat#25]
It looks like the hang is caused somewhere in `_withGlobalStorage()` in both Chromium.app and freeciv-gtk2 hangs. Possibly a threading deadlock?

I've attached the call stack for freeciv-gtk2. The hang occurs in the same place when launching Chromium.app according to the call stack reported by Activity Monitor's process sampler.
[freeciv-gtk2-sample.txt](https://github.com/millenomi/afloat/files/873413/freeciv-gtk2-sample.txt)

```
$ uname -a
Darwin mbp12,1 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
```

**Comment by millenomi** [comment]
Afloat is not supported on Yosemite and later, including El Capitan.
