### ISSUE TITLE
If window is overlay hovering mouse over app should NOT make it opaque

### ISSUE THREAD

**Issue by ProLoser** [millenomi/afloat#3]
Since any interactions performed with the mouse will pass through the window when in overlay mode, even though you might have "make opaque when working with application" turned on, the mouse hover should not trigger opaque behavior.

I click through the app, and in these cases, I want the window to remain translucent. However if I CMD+Tab to the window, then it should become opaque (and _ideally_ clicks should no longer fall through).

**Comment by millenomi** [comment]
Thanks for the contribution, but as no builds are being cut out of this repository I do not accept pull requests. (Branching is obviously fine as long as the license is respected.)

**Comment by ProLoser** [comment]
I've never done Objective-C but I'm skilled in JS and other languages. I'm poking around freenode to see where I can get some help to try to apply this patch myself.

Any chance you could point me at the respective code I should start on that specifically sets the app to opaque open mouse-hover? I imagine that the necessary patch would be trivial and will have to do some rapid-study-hacking to figure it out myself.

**Comment by millenomi** [comment]
It's not trivial, as it should already work like that, but see the ...forWindow:... methods and -beginTrackingWindow:, -endTrackingWindow:, -mouseEntered: and -mouseExited: in Afloat.m.

**Comment by millenomi** [comment]
By which I mean https://github.com/millenomi/afloat/blob/master/Afloat.m
