### ISSUE TITLE
infinite-labs.net/afloat/ 404's

### ISSUE THREAD

**Issue by joshdcomp** [millenomi/afloat#7]
The afloat download page 404's, is there a mirror for that dmg? I'll even host it if you want.

**Comment by millenomi** [comment]
Fixed in LabsNet 7.0.4.

v7.0.4: 
- Add Intents subproject
- Re-add lost Afloat intent URL to the website, redirecting to GitHub.

Note that the lack of a download or a customer-facing page is intentional. See #6.
